/**
* @file {{ api_name }}.cls
* @author Arlanis/{{ creating_user }}
* @reviewedby Arlanis/xxx/yyyy-mm-dd
* @copyright Arlanis Reply AG
* @date {{ release_date }}
* @test ArlTCt{{ base_name }}.cls
* @subject Visualforce controller class {{ api_name }} for page ArlPag{{ base_name }}
* @description TODO
* 
* Change History:
* |    Date          |    Company/Person        |    Description/Reason                             |    Requirement    |
* |------------------|--------------------------|---------------------------------------------------|-------------------|
* |    {{ release_date }}    |    Arlanis/{{ creating_user }}           |    initial release                                |                   |
**/


public with sharing class {{ api_name }} {
	
	
	public {{ api_name }}() {
		// empty initialization
	}
	
	
	// TODO implement methods
	
	
}
